apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc-2
  namespace: llm
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
