apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-volume-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/k8s/volumes/vol2
