apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ollama
  labels:
    app: ollama-proxy
data:
  nginx.conf: |
    events {}

    http {
      map $http_authorization $api_key_valid {
          default                          0;
          "Bearer abc123secret"           1;
      }

      server {
          listen 80;

          location / {
              if ($api_key_valid = 0) {
                  return 403;
              }

              proxy_pass http://ollama:11434;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
    }
