apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-model-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeClaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/ollama-data
  nodeAffinity:
    required:
     nodeSelectorTerms:
       - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values::
              - <NODE_NAME>
