apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-pvc
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
