apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen25-coder-7b
  namespace: llm
  labels:
    app: qwen25-coder-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen25-coder-7b
  template:
    metadata:
      labels:
        app: qwen25-coder-7b
    spec:
      restartPolicy: Always
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args:
          - >
            vllm serve Qwen/Qwen2.5-Coder-7B-Instruct-AWQ
            --quantization=awq
            --tensor-parallel-size=2
            --gpu-memory-utilization=0.85
            --max-model-len=8192
            --trust-remote-code
            --dtype=auto
            --disable-log-requests
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-secret
              key: token
        - name: VLLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: vllm-secret
	      key: token
        ports:
	- containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 2  # Request both GPUs
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: hf-cache
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: hf-cache
        persistentVolumeClaim:
          claimName: cache-pvc-1
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
