apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
        - name: vllm
          image: vllm/vllm-openai:latest
          args:
            - "--model"
            - "$(VLLM_MODEL)"
          env:
            - name: VLLM_MODEL
              valueFrom:
                configMapKeyRef:
                  name: vllm-config
                  key: VLLM_MODEL
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
